# Generated by Django 2.0 on 2017-12-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('obitBN', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dateB', models.DateTimeField(verbose_name='check date')),
                ('commentB', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modbat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modBat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Modups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modUps', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateUB', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UPSB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('released', models.BooleanField(default=False)),
                ('dateU', models.DateTimeField(verbose_name='check date')),
                ('commentU', models.CharField(max_length=100)),
                ('modUps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ups.Modups')),
                ('obitInsBat1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ups.Battery')),
                ('obitInsBat2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ups.Battery')),
                ('obitN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ups.Modups')),
                ('obitOutBat1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ups.Battery')),
                ('obitOutBat2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ups.Battery')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ups.State')),
            ],
        ),
        migrations.AddField(
            model_name='battery',
            name='modBat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ups.Modbat'),
        ),
        migrations.AddField(
            model_name='battery',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ups.State'),
        ),
    ]
