# Generated by Django 2.0 on 2017-12-04 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='modBat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ups.Modbat'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ups.State'),
        ),
        migrations.AlterField(
            model_name='upsb',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ups.State'),
        ),
    ]
