# Generated by Django 2.0 on 2017-12-17 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0003_auto_20171204_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='dateB',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='upsb',
            name='dateU',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
