# Generated by Django 2.0 on 2018-01-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0004_auto_20171217_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='commentB',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='upsb',
            name='commentU',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
